2022-05-31 22:34:23,354 Downloading artifact
2022-05-31 22:34:24,360 Loading the data
Traceback (most recent call last):
  File "/Users/sebastianobando/Documents/UDACITY_MLDevOps/Project 2 - Build an ML Pipeline for Short-term Rental Prices in NYC/src/basic_cleaning/run.py", line 114, in <module>
    go(args)
  File "/Users/sebastianobando/Documents/UDACITY_MLDevOps/Project 2 - Build an ML Pipeline for Short-term Rental Prices in NYC/src/basic_cleaning/run.py", line 31, in go
    df = pd.read_parquet(artifact_local_path)
  File "/Users/sebastianobando/opt/anaconda3/envs/mlflow-39aa411ff480139ab2fc2e94b736e00005acca68/lib/python3.9/site-packages/pandas/io/parquet.py", line 459, in read_parquet
    return impl.read(
  File "/Users/sebastianobando/opt/anaconda3/envs/mlflow-39aa411ff480139ab2fc2e94b736e00005acca68/lib/python3.9/site-packages/pandas/io/parquet.py", line 221, in read
    return self.api.parquet.read_table(
  File "/Users/sebastianobando/opt/anaconda3/envs/mlflow-39aa411ff480139ab2fc2e94b736e00005acca68/lib/python3.9/site-packages/pyarrow/parquet.py", line 1607, in read_table
    dataset = _ParquetDatasetV2(
  File "/Users/sebastianobando/opt/anaconda3/envs/mlflow-39aa411ff480139ab2fc2e94b736e00005acca68/lib/python3.9/site-packages/pyarrow/parquet.py", line 1452, in __init__
    [fragment], schema=fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 761, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: Could not open parquet input source '<Buffer>': Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.